### ISSUE TITLE
Complete Noob, need help!

### ISSUE THREAD

**Issue by christianzappa** [thirug010/Virtual-Tasmota-for-Tuya-api-devices#5]
Hi, trying to do this on a Ubuntu box, very limited experience.

I clone the git to my top level directory and followed the steps, I'm just unable to start the script. The usual response is node can't find it. Any chance for an in-depth walk-thru?

Thanks!

**Comment by thirug010** [comment]
sure I will Video walk through for the installation / initial setup

**Comment by christianzappa** [comment]
@thirug010 any chance you have that video? I guess the bit I'm stuck on is running the nodemon script. I follow your steps but all I get is "- bash: nodemon: command not found"

**Comment by christianzappa** [comment]
worked out how to run it, now I just get this

`Error: Cannot find module 'tuyapi'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Virtual-Tasmota-for-Tuya-api-devices/tuya_api_mqtt.js:162:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by thirug010** [comment]
It looks like you don't have nodemon and/or nodejs installed, Please follow the instructions to install nodejs and nodemon then use the steps in the github. 

1. install nodejs- https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/
2. install nodemon - https://www.npmjs.com/package/nodemon
3. Get the DevID and Local Key - [Here ](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md)
3. Setup the code - [Here](https://github.com/thirug010/Virtual-Tasmota-for-Tuya-api-devices/wiki/Setup-Instructions) from Step 2

**Comment by thirug010** [comment]
try npm install on the code folder should install all dependency including tuya-api
